# Generated by Django 4.0.2 on 2022-12-10 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='img',
            field=models.ImageField(null=True, upload_to='news'),
        ),
    ]
