# Generated by Django 4.0.2 on 2022-12-11 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_news_img'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'ordering': ['title'], 'verbose_name': 'News', 'verbose_name_plural': 'News'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['username'], 'verbose_name': 'User', 'verbose_name_plural': 'Users'},
        ),
    ]
