# Generated by Django 4.0.2 on 2022-12-15 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_comment_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='category',
        ),
        migrations.AddField(
            model_name='news',
            name='category',
            field=models.CharField(choices=[('EVENTO', 'eventos'), ('TALLER', 'talleres'), ('VISITA', 'visitas')], default=1, max_length=100),
        ),
    ]
